project:
  type: website
  output-dir: docs

website:
  title: "Scrollytelling"
  image: preview.png
  twitter-card: true
  open-graph: true

format:
  html:
    page-layout: full
    theme:
      - cosmo.scss
      - custom.scss

